#!/bin/bash

echo "Converting project from Bun to npm..."

# Remove Bun-specific files
echo "Removing Bun files..."
rm -rf bun.lock

# Update package.json scripts to use npm
echo "Updating package.json scripts..."
node -e "
const fs = require('fs');
const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'));

// Update scripts to use npm instead of bun
packageJson.scripts = {
  'dev': 'next dev',
  'build': 'next build',
  'start': 'next start',
  'lint': 'biome check',
  'format': 'biome format --write'
};

fs.writeFileSync('package.json', JSON.stringify(packageJson, null, 2));
"

# Remove package-lock.json if it exists (will be regenerated by npm)
if [ -f "package-lock.json" ]; then
  echo "Removing old package-lock.json..."
  rm package-lock.json
fi

echo "Bun to npm conversion completed successfully!"
echo "Run 'npm install' to install dependencies with npm"
