# Cloudflare Workers configuration
name = "flowslash-api"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard or via CLI)
[vars]
NODE_ENV = "production"

# Secrets (set via: wrangler secret put OPENAI_API_KEY)
# OPENAI_API_KEY = "your-key-here"
# ANTHROPIC_API_KEY = "your-key-here" 
# GOOGLE_API_KEY = "your-key-here"
# COMPOSIO_API_KEY = "your-key-here"

# Resource limits
[limits]
cpu_ms = 30000  # 30 seconds for long-running AI operations

# Development configuration
[env.development]
name = "flowslash-api-dev"
vars = { NODE_ENV = "development" }

# Production configuration  
[env.production]
name = "flowslash-api-prod"
vars = { NODE_ENV = "production" }
